# Generated by Django 4.2.20 on 2025-04-21 04:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_category_order_product_user_birthday_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
