# Generated by Django 4.2.21 on 2025-05-17 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_address_district_remove_address_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating_sample',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
