# Generated by Django 4.2.21 on 2025-05-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='product',
            name='node_name',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
