# Generated by Django 4.2.21 on 2025-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userwatchedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_watch',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
        ),
    ]
